version: '3.7'
services:
  nginx:
    image: nginx
    ports:
      - "8890:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - websrc:/var/www/html/:z
    depends_on:
      - php

  php:
    build:
      context: docker/php
    volumes:
      - websrc:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/extra-php.ini
    user: $UID
    working_dir: /var/www/html
    environment:
      - YELP_ACCESS_TOKEN
      - DATABASE_URL=mysql://myreviews:myreviews1@db:3306/myreviews?serverVersion=5.7
    depends_on:
      - composer

  composer:
    build:
      context: docker/composer
    user: $UID
    volumes:
      - websrc:/app
      - ${COMPOSER_HOME}:/home/composer/.config/composer
      - ${COMPOSER_CACHE_DIR}:/home/composer/.cache/composer
      - ${HOME}/.gitconfig:/home/composer/.gitconfig:Z
    command: composer install
    working_dir: /app
    environment:
      - COMPOSER_HOME=/home/composer
      - HOME=/home/composer

volumes:
  websrc:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $PWD
