monolog:
    channels: ['phpunit_test']
    handlers:
        main:
            type: stream
            path: php://stdout
            level: '%env(LOG_LEVEL)%'
#            formatter: monolog.formatter.json
            channels: ["myreviews_etsy"]
#        main:
#            type: fingers_crossed
#            action_level: error
#            handler: nested
#            excluded_http_codes: [404, 405]
#            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
#        nested:
#            type: stream
#            path: php://stderr
#            level: debug
#            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!phpunit_test"]
